In [1]:
import os
import pathlib
import sys
default_dir_path = str(pathlib.Path(os.getcwd()).parent.absolute())

sys.path.append(default_dir_path)

## Init

In [2]:
from gpu_train import set_random_seed

set_random_seed(random_seed=777)

Global seed set to 777


Set random seed : 777


In [3]:
from ClassificationModule_weighted_sampling import *
from MultiClassification import *
import tqdm.notebook as tqdm

In [4]:
model = MultiClassification(
    learning_rate=0.000005,
    dropout_p=0.3,
    hidden_size=768,
    num_classes=3
)

5e-06 0.3 768 3


In [5]:
dm = ClassificationDataModule(
    batch_size=16,
    train_path='../train.tsv',
    valid_path='../dev.tsv',
    max_length=256, sep='\t',
    doc_col='comments',
    label_col='hate',
    num_workers=1,
    labels_dict={'none' : 0, 'hate' : 1, 'offensive' : 2}
)

In [6]:
checkpoint_callback = pl.callbacks.ModelCheckpoint(
    monitor='val_accuracy',
    dirpath='../bert_hate_multi_chpt_sampling_v3',
    filename='KoBERT/{epoch:02d}-{val_accuracy:.3f}',
    verbose=True,
    save_last=True,
    mode='max',
    save_top_k=-1,
)

In [7]:
tb_logger = pl_loggers.TensorBoardLogger(os.path.join('../bert_hate_multi_chpt_sampling_v3', 'tb_logs'))
lr_logger = pl.callbacks.LearningRateMonitor()

In [8]:
trainer = pl.Trainer(
    default_root_dir='../bert_hate_multi_chpt_sampling_v3/checkpoints',
    logger = tb_logger,
    callbacks = [checkpoint_callback, lr_logger],
    max_epochs=10,
    devices=[3],  # Set device numbers
    accelerator="auto"
    # gpus=1
)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs


In [9]:
trainer.fit(model, dm)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]

  | Name       | Type             | Params
------------------------------------------------
0 | bert       | BertModel        | 92.2 M
1 | dropout    | Dropout          | 0     
2 | linear_4   | Linear           | 98.4 K
3 | linear_5   | Linear           | 387   
4 | metric_acc | Accuracy         | 0     
5 | metric_f1  | F1               | 0     
6 | metric_re

Validation sanity check: 0it [00:00, ?it/s]

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:117: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."
Global seed set to 777


val_accuracy : 0.2577381134033203, val_f1 : 0.24731379747390747, val_recall : 0.2577381134033203, val_precision : 0.3379629850387573


/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:117: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."


Training: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Epoch 0, global step 493: val_accuracy reached 0.51798 (best 0.51798), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v3/KoBERT/epoch=00-val_accuracy=0.518.ckpt" as top 1


val_accuracy : 0.5145150423049927, val_f1 : 0.421996533870697, val_recall : 0.5145150423049927, val_precision : 0.4288632869720459
tensor([2, 2, 1,  ..., 2, 2, 1], device='cuda:3') tensor([1, 1, 1,  ..., 0, 1, 1], device='cuda:3')
torch.Size([7896]) torch.Size([7896])
[Epoch 0 TRAIN] Acc: 0.406619668006897, Prec: 0.41818052530288696, Rec: 0.406619668006897, F1: 0.4063585102558136


Validating: 0it [00:00, ?it/s]

Epoch 1, global step 987: val_accuracy reached 0.56254 (best 0.56254), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v3/KoBERT/epoch=01-val_accuracy=0.563.ckpt" as top 2


val_accuracy : 0.5613713264465332, val_f1 : 0.4795845150947571, val_recall : 0.5613713264465332, val_precision : 0.5210461616516113
tensor([0, 1, 1,  ..., 2, 2, 0], device='cuda:3') tensor([0, 1, 1,  ..., 0, 1, 0], device='cuda:3')
torch.Size([7896]) torch.Size([7896])
[Epoch 1 TRAIN] Acc: 0.5277050137519836, Prec: 0.5506702661514282, Rec: 0.5277050137519836, F1: 0.5068685412406921


Validating: 0it [00:00, ?it/s]

Epoch 2, global step 1481: val_accuracy reached 0.61284 (best 0.61284), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v3/KoBERT/epoch=02-val_accuracy=0.613.ckpt" as top 3


val_accuracy : 0.609682559967041, val_f1 : 0.5868220329284668, val_recall : 0.609682559967041, val_precision : 0.6096208095550537
tensor([2, 1, 1,  ..., 0, 2, 2], device='cuda:3') tensor([1, 1, 1,  ..., 0, 1, 0], device='cuda:3')
torch.Size([7896]) torch.Size([7896])
[Epoch 2 TRAIN] Acc: 0.5857129096984863, Prec: 0.6007109880447388, Rec: 0.5857129096984863, F1: 0.5840165615081787


Validating: 0it [00:00, ?it/s]

Epoch 3, global step 1975: val_accuracy reached 0.60883 (best 0.61284), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v3/KoBERT/epoch=03-val_accuracy=0.609.ckpt" as top 4


val_accuracy : 0.6088712215423584, val_f1 : 0.5738624334335327, val_recall : 0.6088712215423584, val_precision : 0.617332935333252
tensor([0, 1, 2,  ..., 1, 2, 1], device='cuda:3') tensor([2, 1, 1,  ..., 1, 0, 1], device='cuda:3')
torch.Size([7896]) torch.Size([7896])
[Epoch 3 TRAIN] Acc: 0.6285741329193115, Prec: 0.633663535118103, Rec: 0.6285741329193115, F1: 0.6302915215492249


Validating: 0it [00:00, ?it/s]

Epoch 4, global step 2469: val_accuracy reached 0.61934 (best 0.61934), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v3/KoBERT/epoch=04-val_accuracy=0.619.ckpt" as top 5


val_accuracy : 0.6160626411437988, val_f1 : 0.5817785859107971, val_recall : 0.6160626411437988, val_precision : 0.6221601963043213
tensor([1, 0, 2,  ..., 1, 0, 1], device='cuda:3') tensor([2, 0, 2,  ..., 1, 2, 1], device='cuda:3')
torch.Size([7896]) torch.Size([7896])
[Epoch 4 TRAIN] Acc: 0.6684948205947876, Prec: 0.6702759265899658, Rec: 0.6684948205947876, F1: 0.6690022945404053


Validating: 0it [00:00, ?it/s]

Epoch 5, global step 2963: val_accuracy reached 0.62794 (best 0.62794), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v3/KoBERT/epoch=05-val_accuracy=0.628.ckpt" as top 6


val_accuracy : 0.6265785694122314, val_f1 : 0.60480135679245, val_recall : 0.6265785694122314, val_precision : 0.6294136643409729
tensor([0, 0, 2,  ..., 2, 0, 2], device='cuda:3') tensor([0, 2, 2,  ..., 0, 0, 1], device='cuda:3')
torch.Size([7896]) torch.Size([7896])
[Epoch 5 TRAIN] Acc: 0.7041569948196411, Prec: 0.7058539986610413, Rec: 0.7041569948196411, F1: 0.7044910192489624


Validating: 0it [00:00, ?it/s]

Epoch 6, global step 3457: val_accuracy reached 0.62399 (best 0.62794), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v3/KoBERT/epoch=06-val_accuracy=0.624.ckpt" as top 7


val_accuracy : 0.6206261515617371, val_f1 : 0.5879213809967041, val_recall : 0.6206261515617371, val_precision : 0.6282035112380981
tensor([1, 0, 1,  ..., 2, 0, 2], device='cuda:3') tensor([1, 2, 1,  ..., 2, 0, 2], device='cuda:3')
torch.Size([7896]) torch.Size([7896])
[Epoch 6 TRAIN] Acc: 0.7202260494232178, Prec: 0.7191121578216553, Rec: 0.7202260494232178, F1: 0.7192826271057129


Validating: 0it [00:00, ?it/s]

Epoch 7, global step 3951: val_accuracy reached 0.61629 (best 0.62794), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v3/KoBERT/epoch=07-val_accuracy=0.616.ckpt" as top 8


val_accuracy : 0.615149974822998, val_f1 : 0.5875024199485779, val_recall : 0.615149974822998, val_precision : 0.630993664264679
tensor([0, 0, 1,  ..., 0, 1, 2], device='cuda:3') tensor([0, 0, 1,  ..., 2, 1, 2], device='cuda:3')
torch.Size([7896]) torch.Size([7896])
[Epoch 7 TRAIN] Acc: 0.7405615448951721, Prec: 0.7417612671852112, Rec: 0.7405615448951721, F1: 0.7407695651054382


Validating: 0it [00:00, ?it/s]

Epoch 8, global step 4445: val_accuracy reached 0.64098 (best 0.64098), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v3/KoBERT/epoch=08-val_accuracy=0.641.ckpt" as top 9


val_accuracy : 0.6393783688545227, val_f1 : 0.6006655693054199, val_recall : 0.6393783688545227, val_precision : 0.6295899748802185
tensor([2, 1, 2,  ..., 2, 2, 0], device='cuda:3') tensor([2, 1, 0,  ..., 2, 0, 0], device='cuda:3')
torch.Size([7896]) torch.Size([7896])
[Epoch 8 TRAIN] Acc: 0.7570305466651917, Prec: 0.7584936618804932, Rec: 0.7570305466651917, F1: 0.7572284936904907


Validating: 0it [00:00, ?it/s]

Epoch 9, global step 4939: val_accuracy reached 0.63842 (best 0.64098), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v3/KoBERT/epoch=09-val_accuracy=0.638.ckpt" as top 10


val_accuracy : 0.6347795724868774, val_f1 : 0.5960100889205933, val_recall : 0.6347795724868774, val_precision : 0.6307820677757263
tensor([1, 0, 2,  ..., 2, 1, 2], device='cuda:3') tensor([1, 0, 2,  ..., 2, 1, 2], device='cuda:3')
torch.Size([7896]) torch.Size([7896])
[Epoch 9 TRAIN] Acc: 0.7541650533676147, Prec: 0.7555102705955505, Rec: 0.7541650533676147, F1: 0.7544154524803162


Saving latest checkpoint...
