In [1]:
import os
import pathlib
import sys
default_dir_path = str(pathlib.Path(os.getcwd()).parent.absolute())

sys.path.append(default_dir_path)

## Init

In [2]:
from gpu_train import set_random_seed

set_random_seed(random_seed=777)

Global seed set to 777


Set random seed : 777


In [3]:
from ClassificationModule import *
from MultiClassification import *
import tqdm.notebook as tqdm

In [4]:
model = MultiClassification(
    learning_rate=1e-5,
    dropout_p=0.3,
    hidden_size=768,
    num_classes=3
)

1e-05 0.3 768 3


In [5]:
dm = ClassificationDataModule(
    batch_size=16,
    train_path='../train.tsv',
    valid_path='../dev.tsv',
    max_length=256, sep='\t',
    doc_col='comments',
    label_col='hate',
    num_workers=1,
    labels_dict={'none' : 0, 'hate' : 1, 'offensive' : 2}
)

In [6]:
checkpoint_callback = pl.callbacks.ModelCheckpoint(
    monitor='val_accuracy',
    dirpath='../bert_hate_multi_chpt_without_sampling_v2',
    filename='KoBERT/{epoch:02d}-{val_accuracy:.3f}',
    verbose=True,
    save_last=True,
    mode='max',
    save_top_k=-1,
)

In [7]:
tb_logger = pl_loggers.TensorBoardLogger(os.path.join('../bert_hate_multi_chpt_without_sampling_v2', 'tb_logs'))
lr_logger = pl.callbacks.LearningRateMonitor()

In [8]:
trainer = pl.Trainer(
    default_root_dir='../bert_hate_multi_chpt_without_sampling_v2/checkpoints',
    logger = tb_logger,
    callbacks = [checkpoint_callback, lr_logger],
    max_epochs=10,
    devices=[2],  # Set device numbers
    accelerator="auto"
    # gpus=1
)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs


## Training

In [9]:
trainer.fit(model, dm)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]

  | Name       | Type             | Params
------------------------------------------------
0 | bert       | BertModel        | 92.2 M
1 | dropout    | Dropout          | 0     
2 | linear_4   | Linear           | 98.4 K
3 | linear_5   | Linear           | 387   
4 | metric_acc | Accuracy         | 0     
5 | metric_f1  | F1               | 0     
6 | metric_re

Validation sanity check: 0it [00:00, ?it/s]

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:117: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."
Global seed set to 777


val_accuracy : 0.2577381134033203, val_f1 : 0.24731379747390747, val_recall : 0.2577381134033203, val_precision : 0.3379629850387573


/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:117: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."


Training: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Epoch 0, global step 493: val_accuracy reached 0.53249 (best 0.53249), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_without_sampling_v2/KoBERT/epoch=00-val_accuracy=0.532.ckpt" as top 1


val_accuracy : 0.5339639186859131, val_f1 : 0.4677831828594208, val_recall : 0.5339639186859131, val_precision : 0.559435248374939
tensor([2, 0, 2,  ..., 0, 0, 0], device='cuda:2') tensor([1, 1, 2,  ..., 0, 0, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 0 TRAIN] Acc: 0.4808899164199829, Prec: 0.47866567969322205, Rec: 0.4808899164199829, F1: 0.45758041739463806


Validating: 0it [00:00, ?it/s]

Epoch 1, global step 987: val_accuracy reached 0.62796 (best 0.62796), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_without_sampling_v2/KoBERT/epoch=01-val_accuracy=0.628.ckpt" as top 2


val_accuracy : 0.6245150566101074, val_f1 : 0.6017428636550903, val_recall : 0.6245150566101074, val_precision : 0.6455070972442627
tensor([2, 1, 0,  ..., 2, 1, 0], device='cuda:2') tensor([0, 1, 0,  ..., 2, 2, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 1 TRAIN] Acc: 0.6004533767700195, Prec: 0.604193925857544, Rec: 0.6004533767700195, F1: 0.599381148815155


Validating: 0it [00:00, ?it/s]

Epoch 2, global step 1481: val_accuracy reached 0.62349 (best 0.62796), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_without_sampling_v2/KoBERT/epoch=02-val_accuracy=0.623.ckpt" as top 3


val_accuracy : 0.6232628226280212, val_f1 : 0.5947263836860657, val_recall : 0.6232628226280212, val_precision : 0.643348217010498
tensor([2, 2, 2,  ..., 0, 1, 1], device='cuda:2') tensor([2, 1, 0,  ..., 0, 1, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 2 TRAIN] Acc: 0.6830582618713379, Prec: 0.682457685470581, Rec: 0.6830582618713379, F1: 0.6822660565376282


Validating: 0it [00:00, ?it/s]

Epoch 3, global step 1975: val_accuracy reached 0.61898 (best 0.62796), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_without_sampling_v2/KoBERT/epoch=03-val_accuracy=0.619.ckpt" as top 4


val_accuracy : 0.6188360452651978, val_f1 : 0.581895112991333, val_recall : 0.6188360452651978, val_precision : 0.622103214263916
tensor([2, 0, 1,  ..., 2, 0, 1], device='cuda:2') tensor([1, 2, 1,  ..., 0, 0, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 3 TRAIN] Acc: 0.7780460715293884, Prec: 0.7752188444137573, Rec: 0.7780460715293884, F1: 0.7764938473701477


Validating: 0it [00:00, ?it/s]

Epoch 4, global step 2469: val_accuracy reached 0.60188 (best 0.62796), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_without_sampling_v2/KoBERT/epoch=04-val_accuracy=0.602.ckpt" as top 5


val_accuracy : 0.5989286303520203, val_f1 : 0.573788583278656, val_recall : 0.5989286303520203, val_precision : 0.6510145664215088
tensor([2, 0, 1,  ..., 0, 2, 2], device='cuda:2') tensor([2, 0, 1,  ..., 0, 0, 2], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 4 TRAIN] Acc: 0.8294838070869446, Prec: 0.8271893858909607, Rec: 0.8294838070869446, F1: 0.828275740146637


Validating: 0it [00:00, ?it/s]

Epoch 5, global step 2963: val_accuracy reached 0.62344 (best 0.62796), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_without_sampling_v2/KoBERT/epoch=05-val_accuracy=0.623.ckpt" as top 6


val_accuracy : 0.6200794577598572, val_f1 : 0.5962592363357544, val_recall : 0.6200794577598572, val_precision : 0.6539523005485535
tensor([2, 0, 2,  ..., 2, 0, 1], device='cuda:2') tensor([2, 0, 2,  ..., 2, 0, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 5 TRAIN] Acc: 0.8868960738182068, Prec: 0.885019063949585, Rec: 0.8868960738182068, F1: 0.8859372138977051


Validating: 0it [00:00, ?it/s]

Epoch 6, global step 3457: val_accuracy reached 0.62177 (best 0.62796), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_without_sampling_v2/KoBERT/epoch=06-val_accuracy=0.622.ckpt" as top 7


val_accuracy : 0.6184436082839966, val_f1 : 0.5875508785247803, val_recall : 0.6184436082839966, val_precision : 0.6618162393569946
tensor([0, 0, 2,  ..., 0, 0, 1], device='cuda:2') tensor([0, 0, 2,  ..., 0, 0, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 6 TRAIN] Acc: 0.9221330881118774, Prec: 0.9201957583427429, Rec: 0.9221330881118774, F1: 0.9211424589157104


Validating: 0it [00:00, ?it/s]

Epoch 7, global step 3951: val_accuracy reached 0.62870 (best 0.62870), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_without_sampling_v2/KoBERT/epoch=07-val_accuracy=0.629.ckpt" as top 8


val_accuracy : 0.6252425909042358, val_f1 : 0.5997174382209778, val_recall : 0.6252425909042358, val_precision : 0.656397819519043
tensor([2, 0, 1,  ..., 2, 1, 2], device='cuda:2') tensor([2, 0, 1,  ..., 2, 1, 2], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 7 TRAIN] Acc: 0.9449280500411987, Prec: 0.9442235231399536, Rec: 0.9449280500411987, F1: 0.9445699453353882


Validating: 0it [00:00, ?it/s]

Epoch 8, global step 4445: val_accuracy reached 0.61864 (best 0.62870), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_without_sampling_v2/KoBERT/epoch=08-val_accuracy=0.619.ckpt" as top 9


val_accuracy : 0.6153748035430908, val_f1 : 0.5830028057098389, val_recall : 0.6153748035430908, val_precision : 0.6487176418304443
tensor([1, 2, 0,  ..., 0, 2, 0], device='cuda:2') tensor([1, 2, 0,  ..., 0, 2, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 8 TRAIN] Acc: 0.9576146602630615, Prec: 0.9566142559051514, Rec: 0.9576146602630615, F1: 0.957102358341217


Validating: 0it [00:00, ?it/s]

Epoch 9, global step 4939: val_accuracy reached 0.61970 (best 0.62870), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_without_sampling_v2/KoBERT/epoch=09-val_accuracy=0.620.ckpt" as top 10


val_accuracy : 0.6164109706878662, val_f1 : 0.5848458409309387, val_recall : 0.6164109706878662, val_precision : 0.6559873223304749
tensor([0, 2, 0,  ..., 1, 0, 0], device='cuda:2') tensor([0, 2, 0,  ..., 1, 0, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 9 TRAIN] Acc: 0.9618964195251465, Prec: 0.9615408778190613, Rec: 0.9618964195251465, F1: 0.9617179036140442


Saving latest checkpoint...


# Debugging

In [9]:
dm.setup(stage="fit")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.


In [10]:
train_dataloader = dm.train_dataloader()
val_dataloader = dm.val_dataloader()
test_dataloader = dm.test_dataloader()

In [11]:
idx, data = next(enumerate(train_dataloader))

In [12]:
data

{'input_ids': tensor([[   2, 2869, 7402,  ...,    1,    1,    1],
         [   2, 1697, 4471,  ...,    1,    1,    1],
         [   2, 3093, 4206,  ...,    1,    1,    1],
         ...,
         [   2, 3809, 7119,  ...,    1,    1,    1],
         [   2, 3135, 7191,  ...,    1,    1,    1],
         [   2, 1185, 6043,  ...,    1,    1,    1]]),
 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]),
 'label': tensor([1, 2, 0, 2, 0, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2])}

In [13]:
model.training_step(data, idx)

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py:416: UserWarning: You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet. This is most likely because the model hasn't been passed to the `Trainer`
  "You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet."


{'loss': tensor(1.0842, grad_fn=<NllLossBackward>),
 'pred': tensor([0, 2, 1, 2, 0, 2, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1]),
 'label': tensor([1, 2, 0, 2, 0, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2])}

In [14]:
for idx, data in enumerate(tqdm.tqdm(train_dataloader)):
    output_dict = model.training_step(data, idx)
    print(output_dict)
    
    if idx == 10:
        break

  0%|          | 0/494 [00:00<?, ?it/s]

{'loss': tensor(1.1134, grad_fn=<NllLossBackward>), 'pred': tensor([1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 0, 2]), 'label': tensor([0, 1, 0, 2, 2, 0, 0, 0, 0, 1, 2, 0, 2, 0, 2, 1])}
{'loss': tensor(1.0925, grad_fn=<NllLossBackward>), 'pred': tensor([1, 1, 2, 1, 1, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 0]), 'label': tensor([0, 2, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 2, 1, 1])}
{'loss': tensor(1.0754, grad_fn=<NllLossBackward>), 'pred': tensor([2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1]), 'label': tensor([1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1])}
{'loss': tensor(1.1102, grad_fn=<NllLossBackward>), 'pred': tensor([1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]), 'label': tensor([2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 0, 2, 0, 0, 0, 2])}
{'loss': tensor(1.1157, grad_fn=<NllLossBackward>), 'pred': tensor([1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1]), 'label': tensor([2, 1, 0, 0, 0, 1, 0, 2, 2, 1, 0, 2, 1, 2, 0, 2])}


KeyboardInterrupt: 