In [1]:
import os
import pathlib
import sys
default_dir_path = str(pathlib.Path(os.getcwd()).parent.absolute())

sys.path.append(default_dir_path)

## Init

In [2]:
from gpu_train import set_random_seed

set_random_seed(random_seed=777)

Global seed set to 777


Set random seed : 777


In [3]:
from ClassificationModule_weighted_sampling import *
from MultiClassification import *
import tqdm.notebook as tqdm

In [4]:
model = MultiClassification(
    learning_rate=1e-6,
    dropout_p=0.3,
    hidden_size=768,
    num_classes=3
)

1e-06 0.3 768 3


In [5]:
dm = ClassificationDataModule(
    batch_size=16,
    train_path='../train.tsv',
    valid_path='../dev.tsv',
    max_length=256, sep='\t',
    doc_col='comments',
    label_col='hate',
    num_workers=1,
    labels_dict={'none' : 0, 'hate' : 1, 'offensive' : 2}
)

In [6]:
checkpoint_callback = pl.callbacks.ModelCheckpoint(
    monitor='val_accuracy',
    dirpath='../bert_hate_multi_chpt_sampling_v2',
    filename='KoBERT/{epoch:02d}-{val_accuracy:.3f}',
    verbose=True,
    save_last=True,
    mode='max',
    save_top_k=-1,
)

In [7]:
tb_logger = pl_loggers.TensorBoardLogger(os.path.join('../bert_hate_multi_chpt_sampling_v2', 'tb_logs'))
lr_logger = pl.callbacks.LearningRateMonitor()

In [8]:
trainer = pl.Trainer(
    default_root_dir='../bert_hate_multi_chpt_sampling_v2/checkpoints',
    logger = tb_logger,
    callbacks = [checkpoint_callback, lr_logger],
    max_epochs=10,
    devices=[2],  # Set device numbers
    accelerator="auto"
    # gpus=1
)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs


In [9]:
trainer.fit(model, dm)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]

  | Name       | Type             | Params
------------------------------------------------
0 | bert       | BertModel        | 92.2 M
1 | dropout    | Dropout          | 0     
2 | linear_4   | Linear           | 98.4 K
3 | linear_5   | Linear           | 387   
4 | metric_acc | Accuracy         | 0     
5 | metric_f1  | F1               | 0     
6 | metric_re

Validation sanity check: 0it [00:00, ?it/s]

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:117: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."
Global seed set to 777


val_accuracy : 0.2577381134033203, val_f1 : 0.24731379747390747, val_recall : 0.2577381134033203, val_precision : 0.3379629850387573


/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:117: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."


Training: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Epoch 0, global step 493: val_accuracy reached 0.37586 (best 0.37586), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v2/KoBERT/epoch=00-val_accuracy=0.376.ckpt" as top 1


val_accuracy : 0.37714290618896484, val_f1 : 0.34539923071861267, val_recall : 0.37714290618896484, val_precision : 0.3665609061717987
tensor([2, 2, 1,  ..., 2, 2, 1], device='cuda:2') tensor([1, 1, 1,  ..., 0, 2, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 0 TRAIN] Acc: 0.34591448307037354, Prec: 0.34413182735443115, Rec: 0.34591448307037354, F1: 0.3409259617328644


Validating: 0it [00:00, ?it/s]

Epoch 1, global step 987: val_accuracy reached 0.40188 (best 0.40188), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v2/KoBERT/epoch=01-val_accuracy=0.402.ckpt" as top 2


val_accuracy : 0.4005952775478363, val_f1 : 0.3076550364494324, val_recall : 0.4005952775478363, val_precision : 0.30139029026031494
tensor([0, 1, 1,  ..., 2, 2, 0], device='cuda:2') tensor([1, 2, 0,  ..., 2, 1, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 1 TRAIN] Acc: 0.38048428297042847, Prec: 0.3837814927101135, Rec: 0.38048428297042847, F1: 0.3809557557106018


Validating: 0it [00:00, ?it/s]

Epoch 2, global step 1481: val_accuracy reached 0.47536 (best 0.47536), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v2/KoBERT/epoch=02-val_accuracy=0.475.ckpt" as top 3


val_accuracy : 0.4726940393447876, val_f1 : 0.39259013533592224, val_recall : 0.4726940393447876, val_precision : 0.4308812916278839
tensor([2, 1, 1,  ..., 0, 2, 2], device='cuda:2') tensor([1, 1, 0,  ..., 0, 1, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 2 TRAIN] Acc: 0.4064776301383972, Prec: 0.43054836988449097, Rec: 0.4064776301383972, F1: 0.388752818107605


Validating: 0it [00:00, ?it/s]

Epoch 3, global step 1975: val_accuracy reached 0.49028 (best 0.49028), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v2/KoBERT/epoch=03-val_accuracy=0.490.ckpt" as top 4


val_accuracy : 0.48734134435653687, val_f1 : 0.38835906982421875, val_recall : 0.48734134435653687, val_precision : 0.42088061571121216
tensor([0, 1, 2,  ..., 1, 2, 1], device='cuda:2') tensor([1, 1, 1,  ..., 1, 2, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 3 TRAIN] Acc: 0.46170884370803833, Prec: 0.47950732707977295, Rec: 0.46170884370803833, F1: 0.43516844511032104


Validating: 0it [00:00, ?it/s]

Epoch 4, global step 2469: val_accuracy reached 0.51745 (best 0.51745), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v2/KoBERT/epoch=04-val_accuracy=0.517.ckpt" as top 5


val_accuracy : 0.5139947533607483, val_f1 : 0.42123398184776306, val_recall : 0.5139947533607483, val_precision : 0.42491909861564636
tensor([1, 0, 2,  ..., 1, 0, 1], device='cuda:2') tensor([2, 0, 1,  ..., 1, 1, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 4 TRAIN] Acc: 0.46607738733291626, Prec: 0.49886900186538696, Rec: 0.46607738733291626, F1: 0.4454866051673889


Validating: 0it [00:00, ?it/s]

Epoch 5, global step 2963: val_accuracy reached 0.51333 (best 0.51745), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v2/KoBERT/epoch=05-val_accuracy=0.513.ckpt" as top 6


val_accuracy : 0.5099515318870544, val_f1 : 0.43071895837783813, val_recall : 0.5099515318870544, val_precision : 0.47970858216285706
tensor([0, 0, 2,  ..., 2, 0, 2], device='cuda:2') tensor([0, 0, 1,  ..., 0, 0, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 5 TRAIN] Acc: 0.5076255798339844, Prec: 0.5323060154914856, Rec: 0.5076255798339844, F1: 0.48145753145217896


Validating: 0it [00:00, ?it/s]

Epoch 6, global step 3457: val_accuracy reached 0.51841 (best 0.51841), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v2/KoBERT/epoch=06-val_accuracy=0.518.ckpt" as top 7


val_accuracy : 0.5149382948875427, val_f1 : 0.426829993724823, val_recall : 0.5149382948875427, val_precision : 0.45011553168296814
tensor([1, 0, 1,  ..., 2, 0, 2], device='cuda:2') tensor([1, 2, 1,  ..., 2, 0, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 6 TRAIN] Acc: 0.5028877258300781, Prec: 0.5307927131652832, Rec: 0.5028877258300781, F1: 0.4777788519859314


Validating: 0it [00:00, ?it/s]

Epoch 7, global step 3951: val_accuracy reached 0.52897 (best 0.52897), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v2/KoBERT/epoch=07-val_accuracy=0.529.ckpt" as top 8


val_accuracy : 0.5253042578697205, val_f1 : 0.4348561763763428, val_recall : 0.5253042578697205, val_precision : 0.45802754163742065
tensor([0, 0, 1,  ..., 0, 1, 2], device='cuda:2') tensor([0, 0, 1,  ..., 0, 1, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 7 TRAIN] Acc: 0.5101049542427063, Prec: 0.5410647392272949, Rec: 0.5101049542427063, F1: 0.4897061288356781


Validating: 0it [00:00, ?it/s]

Epoch 8, global step 4445: val_accuracy reached 0.53086 (best 0.53086), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v2/KoBERT/epoch=08-val_accuracy=0.531.ckpt" as top 9


val_accuracy : 0.5271561741828918, val_f1 : 0.4383964240550995, val_recall : 0.5271561741828918, val_precision : 0.4661899209022522
tensor([2, 1, 2,  ..., 2, 2, 0], device='cuda:2') tensor([1, 1, 0,  ..., 1, 1, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 8 TRAIN] Acc: 0.510464072227478, Prec: 0.5420989990234375, Rec: 0.510464072227478, F1: 0.48783013224601746


Validating: 0it [00:00, ?it/s]

Epoch 9, global step 4939: val_accuracy reached 0.53369 (best 0.53369), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v2/KoBERT/epoch=09-val_accuracy=0.534.ckpt" as top 10


val_accuracy : 0.5299338698387146, val_f1 : 0.44355592131614685, val_recall : 0.5299338698387146, val_precision : 0.4819246530532837
tensor([1, 0, 2,  ..., 2, 1, 2], device='cuda:2') tensor([1, 0, 1,  ..., 2, 1, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 9 TRAIN] Acc: 0.515347957611084, Prec: 0.5439558029174805, Rec: 0.515347957611084, F1: 0.4911239743232727


Saving latest checkpoint...
