In [1]:
import os
import pathlib
import sys
default_dir_path = str(pathlib.Path(os.getcwd()).parent.absolute())

sys.path.append(default_dir_path)

## Init

In [2]:
from ClassificationModule import *
from MultiClassification import *
import tqdm.notebook as tqdm

In [3]:
model = MultiClassification(
    learning_rate=1e-5,
    dropout_p=0.3,
    hidden_size=768,
    num_classes=3
)

1e-05 0.3 768 3


In [4]:
dm = ClassificationDataModule(
    batch_size=16,
    train_path='../train.tsv',
    valid_path='../dev.tsv',
    max_length=256, sep='\t',
    doc_col='comments',
    label_col='hate',
    num_workers=1,
    labels_dict={'none' : 0, 'hate' : 1, 'offensive' : 2}
)

In [5]:
checkpoint_callback = pl.callbacks.ModelCheckpoint(
    monitor='val_accuracy',
    dirpath='../bert_hate_multi_chpt',
    filename='KoBERT/{epoch:02d}-{val_accuracy:.3f}',
    verbose=True,
    save_last=True,
    mode='max',
    save_top_k=-1,
)

In [6]:
tb_logger = pl_loggers.TensorBoardLogger(os.path.join('../bert_hate_multi_chpt', 'tb_logs'))
lr_logger = pl.callbacks.LearningRateMonitor()

In [7]:
trainer = pl.Trainer(
    default_root_dir='../bert_hate_multi_chpt/checkpoints',
    logger = tb_logger,
    callbacks = [checkpoint_callback, lr_logger],
    max_epochs=10,
    devices=[2],  # Set device numbers
    accelerator="auto"
    # gpus=1
)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs


## Training

In [8]:
trainer.fit(model, dm)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]

  | Name       | Type             | Params
------------------------------------------------
0 | bert       | BertModel        | 92.2 M
1 | dropout    | Dropout          | 0     
2 | linear_4   | Linear           | 98.4 K
3 | linear_5   | Linear           | 387   
4 | metric_acc | Accuracy         | 0     
5 | metric_f1  | F1               | 0     
6 | metric_re

Validation sanity check: 0it [00:00, ?it/s]

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:117: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."


val_accuracy : 0.4222222566604614, val_f1 : 0.3131161332130432, val_recall : 0.4222222566604614, val_precision : 0.3095238208770752


/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:117: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."


Training: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Epoch 0, global step 493: val_accuracy reached 0.50310 (best 0.50310), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt/KoBERT/epoch=00-val_accuracy=0.503.ckpt" as top 1


val_accuracy : 0.5030379295349121, val_f1 : 0.4330599009990692, val_recall : 0.5030379295349121, val_precision : 0.48416224122047424
tensor([1, 2, 1,  ..., 0, 0, 1], device='cuda:2') tensor([2, 2, 2,  ..., 0, 0, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 0 TRAIN] Acc: 0.4510329067707062, Prec: 0.4133961796760559, Rec: 0.4510329067707062, F1: 0.3950340747833252


Validating: 0it [00:00, ?it/s]

Epoch 1, global step 987: val_accuracy reached 0.59618 (best 0.59618), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt/KoBERT/epoch=01-val_accuracy=0.596.ckpt" as top 2


val_accuracy : 0.5943783521652222, val_f1 : 0.5597730278968811, val_recall : 0.5943783521652222, val_precision : 0.6131902933120728
tensor([2, 2, 1,  ..., 2, 0, 0], device='cuda:2') tensor([2, 1, 0,  ..., 2, 0, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 1 TRAIN] Acc: 0.5456893444061279, Prec: 0.5549215078353882, Rec: 0.5456893444061279, F1: 0.5418059229850769


Validating: 0it [00:00, ?it/s]

Epoch 2, global step 1481: val_accuracy reached 0.60111 (best 0.60111), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt/KoBERT/epoch=02-val_accuracy=0.601.ckpt" as top 3


val_accuracy : 0.5992108583450317, val_f1 : 0.5675979852676392, val_recall : 0.5992108583450317, val_precision : 0.6128575801849365
tensor([2, 1, 1,  ..., 2, 1, 2], device='cuda:2') tensor([1, 2, 1,  ..., 2, 1, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 2 TRAIN] Acc: 0.6094146370887756, Prec: 0.6090000867843628, Rec: 0.6094146370887756, F1: 0.608407199382782


Validating: 0it [00:00, ?it/s]

Epoch 3, global step 1975: val_accuracy reached 0.63501 (best 0.63501), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt/KoBERT/epoch=03-val_accuracy=0.635.ckpt" as top 4


val_accuracy : 0.634559154510498, val_f1 : 0.5790008902549744, val_recall : 0.634559154510498, val_precision : 0.6113272309303284
tensor([0, 2, 2,  ..., 2, 1, 0], device='cuda:2') tensor([2, 1, 2,  ..., 1, 1, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 3 TRAIN] Acc: 0.6538802981376648, Prec: 0.6493473052978516, Rec: 0.6538802981376648, F1: 0.6512834429740906


Validating: 0it [00:00, ?it/s]

Epoch 4, global step 2469: val_accuracy reached 0.61391 (best 0.63501), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt/KoBERT/epoch=04-val_accuracy=0.614.ckpt" as top 5


val_accuracy : 0.6107318997383118, val_f1 : 0.5905832648277283, val_recall : 0.6107318997383118, val_precision : 0.6347090601921082
tensor([2, 1, 0,  ..., 2, 1, 0], device='cuda:2') tensor([0, 2, 0,  ..., 0, 0, 2], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 4 TRAIN] Acc: 0.6891181468963623, Prec: 0.6857180595397949, Rec: 0.6891181468963623, F1: 0.6873066425323486


Validating: 0it [00:00, ?it/s]

Epoch 5, global step 2963: val_accuracy reached 0.61882 (best 0.63501), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt/KoBERT/epoch=05-val_accuracy=0.619.ckpt" as top 6


val_accuracy : 0.6155468225479126, val_f1 : 0.5844963192939758, val_recall : 0.6155468225479126, val_precision : 0.6225529909133911
tensor([2, 0, 0,  ..., 0, 2, 0], device='cuda:2') tensor([2, 2, 0,  ..., 0, 0, 2], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 5 TRAIN] Acc: 0.7247954607009888, Prec: 0.7216827273368835, Rec: 0.7247954607009888, F1: 0.7231667637825012


Validating: 0it [00:00, ?it/s]

Epoch 6, global step 3457: val_accuracy reached 0.62921 (best 0.63501), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt/KoBERT/epoch=06-val_accuracy=0.629.ckpt" as top 7


val_accuracy : 0.6278308033943176, val_f1 : 0.6021503806114197, val_recall : 0.6278308033943176, val_precision : 0.62059086561203
tensor([1, 2, 0,  ..., 1, 1, 0], device='cuda:2') tensor([1, 1, 0,  ..., 1, 1, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 6 TRAIN] Acc: 0.7565039396286011, Prec: 0.7544583082199097, Rec: 0.7565039396286011, F1: 0.755447268486023


Validating: 0it [00:00, ?it/s]

Epoch 7, global step 3951: val_accuracy reached 0.59559 (best 0.63501), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt/KoBERT/epoch=07-val_accuracy=0.596.ckpt" as top 8


val_accuracy : 0.5927557945251465, val_f1 : 0.5643013119697571, val_recall : 0.5927557945251465, val_precision : 0.6109745502471924
tensor([2, 2, 1,  ..., 0, 1, 2], device='cuda:2') tensor([1, 2, 1,  ..., 0, 1, 1], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 7 TRAIN] Acc: 0.7936533689498901, Prec: 0.7915418148040771, Rec: 0.7936533689498901, F1: 0.7925212979316711


Validating: 0it [00:00, ?it/s]

Epoch 8, global step 4445: val_accuracy reached 0.62993 (best 0.63501), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt/KoBERT/epoch=08-val_accuracy=0.630.ckpt" as top 9


val_accuracy : 0.6264506578445435, val_f1 : 0.5929643511772156, val_recall : 0.6264506578445435, val_precision : 0.6283726692199707
tensor([0, 0, 0,  ..., 2, 2, 0], device='cuda:2') tensor([0, 0, 0,  ..., 0, 2, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 8 TRAIN] Acc: 0.8204229474067688, Prec: 0.8182611465454102, Rec: 0.8204229474067688, F1: 0.8192453980445862


Validating: 0it [00:00, ?it/s]

Epoch 9, global step 4939: val_accuracy reached 0.62270 (best 0.63501), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt/KoBERT/epoch=09-val_accuracy=0.623.ckpt" as top 10


val_accuracy : 0.6193607449531555, val_f1 : 0.5848963856697083, val_recall : 0.6193607449531555, val_precision : 0.6350144743919373
tensor([0, 0, 0,  ..., 1, 0, 0], device='cuda:2') tensor([0, 0, 2,  ..., 1, 0, 0], device='cuda:2')
torch.Size([7896]) torch.Size([7896])
[Epoch 9 TRAIN] Acc: 0.8383643627166748, Prec: 0.8378006815910339, Rec: 0.8383643627166748, F1: 0.8380794525146484


Saving latest checkpoint...


# Debugging

In [9]:
dm.setup(stage="fit")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.


In [10]:
train_dataloader = dm.train_dataloader()
val_dataloader = dm.val_dataloader()
test_dataloader = dm.test_dataloader()

In [11]:
idx, data = next(enumerate(train_dataloader))

In [12]:
data

{'input_ids': tensor([[   2, 2869, 7402,  ...,    1,    1,    1],
         [   2, 1697, 4471,  ...,    1,    1,    1],
         [   2, 3093, 4206,  ...,    1,    1,    1],
         ...,
         [   2, 3809, 7119,  ...,    1,    1,    1],
         [   2, 3135, 7191,  ...,    1,    1,    1],
         [   2, 1185, 6043,  ...,    1,    1,    1]]),
 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]),
 'label': tensor([1, 2, 0, 2, 0, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2])}

In [13]:
model.training_step(data, idx)

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py:416: UserWarning: You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet. This is most likely because the model hasn't been passed to the `Trainer`
  "You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet."


{'loss': tensor(1.0842, grad_fn=<NllLossBackward>),
 'pred': tensor([0, 2, 1, 2, 0, 2, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1]),
 'label': tensor([1, 2, 0, 2, 0, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2])}

In [14]:
for idx, data in enumerate(tqdm.tqdm(train_dataloader)):
    output_dict = model.training_step(data, idx)
    print(output_dict)
    
    if idx == 10:
        break

  0%|          | 0/494 [00:00<?, ?it/s]

{'loss': tensor(1.1134, grad_fn=<NllLossBackward>), 'pred': tensor([1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 0, 2]), 'label': tensor([0, 1, 0, 2, 2, 0, 0, 0, 0, 1, 2, 0, 2, 0, 2, 1])}
{'loss': tensor(1.0925, grad_fn=<NllLossBackward>), 'pred': tensor([1, 1, 2, 1, 1, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 0]), 'label': tensor([0, 2, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 2, 1, 1])}
{'loss': tensor(1.0754, grad_fn=<NllLossBackward>), 'pred': tensor([2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1]), 'label': tensor([1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1])}
{'loss': tensor(1.1102, grad_fn=<NllLossBackward>), 'pred': tensor([1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]), 'label': tensor([2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 0, 2, 0, 0, 0, 2])}
{'loss': tensor(1.1157, grad_fn=<NllLossBackward>), 'pred': tensor([1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1]), 'label': tensor([2, 1, 0, 0, 0, 1, 0, 2, 2, 1, 0, 2, 1, 2, 0, 2])}


KeyboardInterrupt: 