In [1]:
import os
import pathlib
import sys
default_dir_path = str(pathlib.Path(os.getcwd()).parent.absolute())

sys.path.append(default_dir_path)

## Init

In [2]:
from gpu_train import set_random_seed

set_random_seed(random_seed=777)

Global seed set to 777


Set random seed : 777


In [3]:
from ClassificationModule_weighted_sampling import *
from MultiClassification import *
import tqdm.notebook as tqdm

In [4]:
model = MultiClassification(
    learning_rate=1e-5,
    dropout_p=0.3,
    hidden_size=768,
    num_classes=3
)

1e-05 0.3 768 3


In [5]:
dm = ClassificationDataModule(
    batch_size=16,
    train_path='../train.tsv',
    valid_path='../dev.tsv',
    max_length=256, sep='\t',
    doc_col='comments',
    label_col='hate',
    num_workers=1,
    labels_dict={'none' : 0, 'hate' : 1, 'offensive' : 2}
)

In [6]:
checkpoint_callback = pl.callbacks.ModelCheckpoint(
    monitor='val_accuracy',
    dirpath='../bert_hate_multi_chpt_sampling_v1',
    filename='KoBERT/{epoch:02d}-{val_accuracy:.3f}',
    verbose=True,
    save_last=True,
    mode='max',
    save_top_k=-1,
)

In [7]:
tb_logger = pl_loggers.TensorBoardLogger(os.path.join('../bert_hate_multi_chpt_sampling_v1', 'tb_logs'))
lr_logger = pl.callbacks.LearningRateMonitor()

In [8]:
trainer = pl.Trainer(
    default_root_dir='../bert_hate_multi_chpt_sampling_v1/checkpoints',
    logger = tb_logger,
    callbacks = [checkpoint_callback, lr_logger],
    max_epochs=10,
    devices=[1],  # Set device numbers
    accelerator="auto"
    # gpus=1
)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs


In [9]:
trainer.fit(model, dm)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]

  | Name       | Type             | Params
------------------------------------------------
0 | bert       | BertModel        | 92.2 M
1 | dropout    | Dropout          | 0     
2 | linear_4   | Linear           | 98.4 K
3 | linear_5   | Linear           | 387   
4 | metric_acc | Accuracy         | 0     
5 | metric_f1  | F1               | 0     
6 | metric_re

Validation sanity check: 0it [00:00, ?it/s]

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:117: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."
Global seed set to 777


val_accuracy : 0.2577381134033203, val_f1 : 0.24731379747390747, val_recall : 0.2577381134033203, val_precision : 0.3379629850387573


/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:117: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."


Training: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Epoch 0, global step 493: val_accuracy reached 0.56208 (best 0.56208), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v1/KoBERT/epoch=00-val_accuracy=0.562.ckpt" as top 1


val_accuracy : 0.5609127283096313, val_f1 : 0.4954640865325928, val_recall : 0.5609127283096313, val_precision : 0.5581507086753845
tensor([2, 2, 1,  ..., 2, 2, 1], device='cuda:1') tensor([1, 1, 1,  ..., 2, 2, 1], device='cuda:1')
torch.Size([7896]) torch.Size([7896])
[Epoch 0 TRAIN] Acc: 0.4485624432563782, Prec: 0.4700823128223419, Rec: 0.4485624432563782, F1: 0.442568838596344


Validating: 0it [00:00, ?it/s]

Epoch 1, global step 987: val_accuracy reached 0.59554 (best 0.59554), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v1/KoBERT/epoch=01-val_accuracy=0.596.ckpt" as top 2


val_accuracy : 0.5937522649765015, val_f1 : 0.546039879322052, val_recall : 0.5937522649765015, val_precision : 0.5909476280212402
tensor([0, 1, 1,  ..., 2, 2, 0], device='cuda:1') tensor([2, 1, 1,  ..., 0, 2, 0], device='cuda:1')
torch.Size([7896]) torch.Size([7896])
[Epoch 1 TRAIN] Acc: 0.5867426991462708, Prec: 0.6016863584518433, Rec: 0.5867426991462708, F1: 0.5866506695747375


Validating: 0it [00:00, ?it/s]

Epoch 2, global step 1481: val_accuracy reached 0.62314 (best 0.62314), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v1/KoBERT/epoch=02-val_accuracy=0.623.ckpt" as top 3


val_accuracy : 0.6239550709724426, val_f1 : 0.6100941896438599, val_recall : 0.6239550709724426, val_precision : 0.6523661613464355
tensor([2, 1, 1,  ..., 0, 2, 2], device='cuda:1') tensor([2, 1, 1,  ..., 0, 2, 0], device='cuda:1')
torch.Size([7896]) torch.Size([7896])
[Epoch 2 TRAIN] Acc: 0.6581666469573975, Prec: 0.661769688129425, Rec: 0.6581666469573975, F1: 0.6595110893249512


Validating: 0it [00:00, ?it/s]

Epoch 3, global step 1975: val_accuracy reached 0.62892 (best 0.62892), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v1/KoBERT/epoch=03-val_accuracy=0.629.ckpt" as top 4


val_accuracy : 0.6296252608299255, val_f1 : 0.6054778099060059, val_recall : 0.6296252608299255, val_precision : 0.6297222375869751
tensor([0, 1, 2,  ..., 1, 2, 1], device='cuda:1') tensor([0, 1, 1,  ..., 1, 0, 1], device='cuda:1')
torch.Size([7896]) torch.Size([7896])
[Epoch 3 TRAIN] Acc: 0.7133290767669678, Prec: 0.711056113243103, Rec: 0.7133290767669678, F1: 0.7119423747062683


Validating: 0it [00:00, ?it/s]

Epoch 4, global step 2469: val_accuracy reached 0.64223 (best 0.64223), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v1/KoBERT/epoch=04-val_accuracy=0.642.ckpt" as top 5


val_accuracy : 0.641649067401886, val_f1 : 0.6110130548477173, val_recall : 0.641649067401886, val_precision : 0.6409207582473755
tensor([1, 0, 2,  ..., 1, 0, 1], device='cuda:1') tensor([2, 2, 2,  ..., 2, 2, 1], device='cuda:1')
torch.Size([7896]) torch.Size([7896])
[Epoch 4 TRAIN] Acc: 0.7505286931991577, Prec: 0.7479265928268433, Rec: 0.7505286931991577, F1: 0.7488970756530762


Validating: 0it [00:00, ?it/s]

Epoch 5, global step 2963: val_accuracy reached 0.64255 (best 0.64255), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v1/KoBERT/epoch=05-val_accuracy=0.643.ckpt" as top 6


val_accuracy : 0.640917181968689, val_f1 : 0.6181933283805847, val_recall : 0.640917181968689, val_precision : 0.6472856402397156
tensor([0, 0, 2,  ..., 2, 0, 2], device='cuda:1') tensor([0, 0, 2,  ..., 2, 0, 1], device='cuda:1')
torch.Size([7896]) torch.Size([7896])
[Epoch 5 TRAIN] Acc: 0.7868088483810425, Prec: 0.7858148813247681, Rec: 0.7868088483810425, F1: 0.7860456705093384


Validating: 0it [00:00, ?it/s]

Epoch 6, global step 3457: val_accuracy reached 0.61213 (best 0.64255), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v1/KoBERT/epoch=06-val_accuracy=0.612.ckpt" as top 7


val_accuracy : 0.608985960483551, val_f1 : 0.5910860896110535, val_recall : 0.608985960483551, val_precision : 0.6360758543014526
tensor([1, 0, 1,  ..., 2, 0, 2], device='cuda:1') tensor([1, 0, 1,  ..., 2, 0, 2], device='cuda:1')
torch.Size([7896]) torch.Size([7896])
[Epoch 6 TRAIN] Acc: 0.8181604146957397, Prec: 0.8171764016151428, Rec: 0.8181604146957397, F1: 0.8174968957901001


Validating: 0it [00:00, ?it/s]

Epoch 7, global step 3951: val_accuracy reached 0.63716 (best 0.64255), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v1/KoBERT/epoch=07-val_accuracy=0.637.ckpt" as top 8


val_accuracy : 0.6335493922233582, val_f1 : 0.608532726764679, val_recall : 0.6335493922233582, val_precision : 0.6478840112686157
tensor([0, 0, 1,  ..., 0, 1, 2], device='cuda:1') tensor([0, 0, 2,  ..., 2, 1, 2], device='cuda:1')
torch.Size([7896]) torch.Size([7896])
[Epoch 7 TRAIN] Acc: 0.8439788818359375, Prec: 0.8440084457397461, Rec: 0.8439788818359375, F1: 0.8438670635223389


Validating: 0it [00:00, ?it/s]

Epoch 8, global step 4445: val_accuracy reached 0.62734 (best 0.64255), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v1/KoBERT/epoch=08-val_accuracy=0.627.ckpt" as top 9


val_accuracy : 0.6239153742790222, val_f1 : 0.5926197171211243, val_recall : 0.6239153742790222, val_precision : 0.6230551600456238
tensor([2, 1, 2,  ..., 2, 2, 0], device='cuda:1') tensor([2, 1, 2,  ..., 2, 2, 0], device='cuda:1')
torch.Size([7896]) torch.Size([7896])
[Epoch 8 TRAIN] Acc: 0.8606960773468018, Prec: 0.8596621155738831, Rec: 0.8606960773468018, F1: 0.8599783182144165


Validating: 0it [00:00, ?it/s]

Epoch 9, global step 4939: val_accuracy reached 0.61964 (best 0.64255), saving model to "/workspace/Project/KoBERTMultiClassification/bert_hate_multi_chpt_sampling_v1/KoBERT/epoch=09-val_accuracy=0.620.ckpt" as top 10


val_accuracy : 0.6163581013679504, val_f1 : 0.5909029245376587, val_recall : 0.6163581013679504, val_precision : 0.6288400292396545
tensor([1, 0, 2,  ..., 2, 1, 2], device='cuda:1') tensor([1, 0, 2,  ..., 2, 1, 1], device='cuda:1')
torch.Size([7896]) torch.Size([7896])
[Epoch 9 TRAIN] Acc: 0.8683687448501587, Prec: 0.8682719469070435, Rec: 0.8683687448501587, F1: 0.8681714534759521


Saving latest checkpoint...


# Debugging

In [8]:
dm.setup(stage="fit")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'XLNetTokenizer'. 
The class this function is called from is 'KoBERTTokenizer'.


In [22]:
def get_sample_weights(dataset):
    class_count_list = [0, 0, 0]
    
    for data in dataset:
        label = data["label"]
        class_count_list[label] += 1

    class_weight_list = 1. / torch.Tensor(class_count_list)

    sample_weights = [class_weight_list[class_idx] for class_idx in [int(data["label"]) for data in dataset]]

    return sample_weights

In [23]:
train_dataset = dm.set_train
val_dataset = dm.set_valid

In [24]:
train_sample_weights = get_sample_weights(dataset=train_dataset)

In [15]:
train_dataset[0]

{'input_ids': tensor([   2,  522, 7906, 5095, 7276, 7119, 3060, 7227,   40, 3093,  115, 1406,
         1907, 6115, 7796, 6896, 1407, 6353, 6015, 6166, 5439, 5095, 6165, 7784,
         6542, 5422, 5761, 1526, 5512,  984, 4541, 6213, 6288, 5702,   54,   55,
            3,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1, 

In [10]:
dm.__dict__

{'prepare_data': <function pytorch_lightning.core.hooks.DataHooks.prepare_data() -> None>,
 'setup': <function ClassificationModule.ClassificationDataModule.setup(stage=None)>,
 'teardown': <function pytorch_lightning.core.hooks.DataHooks.teardown(stage: Union[str, NoneType] = None) -> None>,
 '_log_hyperparams': False,
 'prepare_data_per_node': True,
 'allow_zero_length_dataloader_with_multiple_devices': False,
 '_train_transforms': None,
 '_val_transforms': None,
 '_test_transforms': None,
 '_dims': (),
 'trainer': None,
 '_has_prepared_data': False,
 '_has_setup_fit': True,
 '_has_setup_validate': False,
 '_has_setup_test': False,
 '_has_setup_predict': False,
 '_has_teardown_fit': False,
 '_has_teardown_validate': False,
 '_has_teardown_test': False,
 '_has_teardown_predict': False,
 'batch_size': 16,
 'train_path': '../train.tsv',
 'valid_path': '../dev.tsv',
 'max_length': 256,
 'doc_col': 'comments',
 'label_col': 'hate',
 'sep': '\t',
 'num_workers': 1,
 'labels_dict': {'none':

In [10]:
train_dataloader = dm.train_dataloader()
val_dataloader = dm.val_dataloader()
test_dataloader = dm.test_dataloader()

In [11]:
idx, data = next(enumerate(train_dataloader))

In [12]:
data

{'input_ids': tensor([[   2, 2869, 7402,  ...,    1,    1,    1],
         [   2, 1697, 4471,  ...,    1,    1,    1],
         [   2, 3093, 4206,  ...,    1,    1,    1],
         ...,
         [   2, 3809, 7119,  ...,    1,    1,    1],
         [   2, 3135, 7191,  ...,    1,    1,    1],
         [   2, 1185, 6043,  ...,    1,    1,    1]]),
 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]),
 'label': tensor([1, 2, 0, 2, 0, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2])}

In [13]:
model.training_step(data, idx)

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py:416: UserWarning: You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet. This is most likely because the model hasn't been passed to the `Trainer`
  "You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet."


{'loss': tensor(1.0842, grad_fn=<NllLossBackward>),
 'pred': tensor([0, 2, 1, 2, 0, 2, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1]),
 'label': tensor([1, 2, 0, 2, 0, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2])}

In [14]:
for idx, data in enumerate(tqdm.tqdm(train_dataloader)):
    output_dict = model.training_step(data, idx)
    print(output_dict)
    
    if idx == 10:
        break

  0%|          | 0/494 [00:00<?, ?it/s]

{'loss': tensor(1.1134, grad_fn=<NllLossBackward>), 'pred': tensor([1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 0, 2]), 'label': tensor([0, 1, 0, 2, 2, 0, 0, 0, 0, 1, 2, 0, 2, 0, 2, 1])}
{'loss': tensor(1.0925, grad_fn=<NllLossBackward>), 'pred': tensor([1, 1, 2, 1, 1, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 0]), 'label': tensor([0, 2, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 2, 1, 1])}
{'loss': tensor(1.0754, grad_fn=<NllLossBackward>), 'pred': tensor([2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1]), 'label': tensor([1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1])}
{'loss': tensor(1.1102, grad_fn=<NllLossBackward>), 'pred': tensor([1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]), 'label': tensor([2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 0, 2, 0, 0, 0, 2])}
{'loss': tensor(1.1157, grad_fn=<NllLossBackward>), 'pred': tensor([1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1]), 'label': tensor([2, 1, 0, 0, 0, 1, 0, 2, 2, 1, 0, 2, 1, 2, 0, 2])}


KeyboardInterrupt: 